addons:
  apt:
    packages:
      - libjpeg62

language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/build_dials
  timeout: 1000

jobs:
  include:
    - stage: build
      before_install:
         # Validate cache
         - ./.travis/cache-make-snapshot

      install:
         # Setup a base installation
         - ./.travis/setup-base

         # Inject DXTBX
         - rm -rf $HOME/build_dials/modules/dxtbx
         - mv $HOME/build/cctbx/dxtbx $HOME/build_dials/modules/dxtbx

      before_script:
         # Enter CCTBX environment
         - cat $HOME/build_dials/build/setpaths.sh
         - cd $HOME/build_dials/build
         - . setpaths.sh

         # Prepare for the build step
         - libtbx.configure .

      script:
         # Parallel builds do not work. Only spend at most 40 minutes on a build.
         # This allows incremental building, so if the build can't be finished within the allotted time
         # it will be resumed from that point in the next build.
         - $HOME/build_dials/modules/dxtbx/.travis/build-for 40m

before_cache:
  - cd $HOME
  - $HOME/build_dials/modules/dxtbx/.travis/cache-validate-snapshot
  - rm -rf $HOME/build_dials/modules/dxtbx
